package com.dreamingCourse.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Course {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_course.id
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_course.tag_id
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private Integer tagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_course.name
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_course.subtitle
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private String subtitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_course.main_image
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private String mainImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_course.activity_price
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private Long activityPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_course.price
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_course.create_time
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_course.update_time
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_course.status
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_course.is_alive
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private Integer isAlive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_course.sub_images
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private String subImages;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_course.detail
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private String detail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_course.id
     *
     * @return the value of ykt_course.id
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_course.id
     *
     * @param id the value for ykt_course.id
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_course.tag_id
     *
     * @return the value of ykt_course.tag_id
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public Integer getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_course.tag_id
     *
     * @param tagId the value for ykt_course.tag_id
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_course.name
     *
     * @return the value of ykt_course.name
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_course.name
     *
     * @param name the value for ykt_course.name
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_course.subtitle
     *
     * @return the value of ykt_course.subtitle
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public String getSubtitle() {
        return subtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_course.subtitle
     *
     * @param subtitle the value for ykt_course.subtitle
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle == null ? null : subtitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_course.main_image
     *
     * @return the value of ykt_course.main_image
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public String getMainImage() {
        return mainImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_course.main_image
     *
     * @param mainImage the value for ykt_course.main_image
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setMainImage(String mainImage) {
        this.mainImage = mainImage == null ? null : mainImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_course.activity_price
     *
     * @return the value of ykt_course.activity_price
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public Long getActivityPrice() {
        return activityPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_course.activity_price
     *
     * @param activityPrice the value for ykt_course.activity_price
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setActivityPrice(Long activityPrice) {
        this.activityPrice = activityPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_course.price
     *
     * @return the value of ykt_course.price
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_course.price
     *
     * @param price the value for ykt_course.price
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_course.create_time
     *
     * @return the value of ykt_course.create_time
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_course.create_time
     *
     * @param createTime the value for ykt_course.create_time
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_course.update_time
     *
     * @return the value of ykt_course.update_time
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_course.update_time
     *
     * @param updateTime the value for ykt_course.update_time
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_course.status
     *
     * @return the value of ykt_course.status
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_course.status
     *
     * @param status the value for ykt_course.status
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_course.is_alive
     *
     * @return the value of ykt_course.is_alive
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public Integer getIsAlive() {
        return isAlive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_course.is_alive
     *
     * @param isAlive the value for ykt_course.is_alive
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setIsAlive(Integer isAlive) {
        this.isAlive = isAlive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_course.sub_images
     *
     * @return the value of ykt_course.sub_images
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public String getSubImages() {
        return subImages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_course.sub_images
     *
     * @param subImages the value for ykt_course.sub_images
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setSubImages(String subImages) {
        this.subImages = subImages == null ? null : subImages.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_course.detail
     *
     * @return the value of ykt_course.detail
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_course.detail
     *
     * @param detail the value for ykt_course.detail
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }
}