package com.dreamingCourse.entity;

public class Lists {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_list.id
     *
     * @mbggenerated Mon Aug 12 21:15:46 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_list.course_id
     *
     * @mbggenerated Mon Aug 12 21:15:46 CST 2019
     */
    private Integer courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_list.chapter
     *
     * @mbggenerated Mon Aug 12 21:15:46 CST 2019
     */
    private Integer chapter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_list.node
     *
     * @mbggenerated Mon Aug 12 21:15:46 CST 2019
     */
    private Integer node;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_list.video_link
     *
     * @mbggenerated Mon Aug 12 21:15:46 CST 2019
     */
    private String videoLink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_list.is_alive
     *
     * @mbggenerated Mon Aug 12 21:15:46 CST 2019
     */
    private Integer isAlive;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_list.id
     *
     * @return the value of ykt_list.id
     *
     * @mbggenerated Mon Aug 12 21:15:46 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_list.id
     *
     * @param id the value for ykt_list.id
     *
     * @mbggenerated Mon Aug 12 21:15:46 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_list.course_id
     *
     * @return the value of ykt_list.course_id
     *
     * @mbggenerated Mon Aug 12 21:15:46 CST 2019
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_list.course_id
     *
     * @param courseId the value for ykt_list.course_id
     *
     * @mbggenerated Mon Aug 12 21:15:46 CST 2019
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_list.chapter
     *
     * @return the value of ykt_list.chapter
     *
     * @mbggenerated Mon Aug 12 21:15:46 CST 2019
     */
    public Integer getChapter() {
        return chapter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_list.chapter
     *
     * @param chapter the value for ykt_list.chapter
     *
     * @mbggenerated Mon Aug 12 21:15:46 CST 2019
     */
    public void setChapter(Integer chapter) {
        this.chapter = chapter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_list.node
     *
     * @return the value of ykt_list.node
     *
     * @mbggenerated Mon Aug 12 21:15:46 CST 2019
     */
    public Integer getNode() {
        return node;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_list.node
     *
     * @param node the value for ykt_list.node
     *
     * @mbggenerated Mon Aug 12 21:15:46 CST 2019
     */
    public void setNode(Integer node) {
        this.node = node;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_list.video_link
     *
     * @return the value of ykt_list.video_link
     *
     * @mbggenerated Mon Aug 12 21:15:46 CST 2019
     */
    public String getVideoLink() {
        return videoLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_list.video_link
     *
     * @param videoLink the value for ykt_list.video_link
     *
     * @mbggenerated Mon Aug 12 21:15:46 CST 2019
     */
    public void setVideoLink(String videoLink) {
        this.videoLink = videoLink == null ? null : videoLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_list.is_alive
     *
     * @return the value of ykt_list.is_alive
     *
     * @mbggenerated Mon Aug 12 21:15:46 CST 2019
     */
    public Integer getIsAlive() {
        return isAlive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_list.is_alive
     *
     * @param isAlive the value for ykt_list.is_alive
     *
     * @mbggenerated Mon Aug 12 21:15:46 CST 2019
     */
    public void setIsAlive(Integer isAlive) {
        this.isAlive = isAlive;
    }
}