package com.dreamingCourse.entity;

import java.util.Date;

public class Notice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_notice.id
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_notice.ntitle
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private String ntitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_notice.ncontent
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private String ncontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_notice.ntime
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private Date ntime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_notice.id
     *
     * @return the value of ykt_notice.id
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_notice.id
     *
     * @param id the value for ykt_notice.id
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_notice.ntitle
     *
     * @return the value of ykt_notice.ntitle
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public String getNtitle() {
        return ntitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_notice.ntitle
     *
     * @param ntitle the value for ykt_notice.ntitle
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setNtitle(String ntitle) {
        this.ntitle = ntitle == null ? null : ntitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_notice.ncontent
     *
     * @return the value of ykt_notice.ncontent
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public String getNcontent() {
        return ncontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_notice.ncontent
     *
     * @param ncontent the value for ykt_notice.ncontent
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setNcontent(String ncontent) {
        this.ncontent = ncontent == null ? null : ncontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_notice.ntime
     *
     * @return the value of ykt_notice.ntime
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public Date getNtime() {
        return ntime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_notice.ntime
     *
     * @param ntime the value for ykt_notice.ntime
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setNtime(Date ntime) {
        this.ntime = ntime;
    }
}