package com.dreamingCourse.entity;

import java.math.BigDecimal;

public class OrderItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_order_item.id
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_order_item.course_id
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private Integer courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_order_item.order_id
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_order_item.current_unit_price
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private BigDecimal currentUnitPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_order_item.quantity
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_order_item.is_alive
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private Integer isAlive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_order_item.user_id
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_order_item.id
     *
     * @return the value of ykt_order_item.id
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_order_item.id
     *
     * @param id the value for ykt_order_item.id
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_order_item.course_id
     *
     * @return the value of ykt_order_item.course_id
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_order_item.course_id
     *
     * @param courseId the value for ykt_order_item.course_id
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_order_item.order_id
     *
     * @return the value of ykt_order_item.order_id
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_order_item.order_id
     *
     * @param orderId the value for ykt_order_item.order_id
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_order_item.current_unit_price
     *
     * @return the value of ykt_order_item.current_unit_price
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public BigDecimal getCurrentUnitPrice() {
        return currentUnitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_order_item.current_unit_price
     *
     * @param currentUnitPrice the value for ykt_order_item.current_unit_price
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setCurrentUnitPrice(BigDecimal currentUnitPrice) {
        this.currentUnitPrice = currentUnitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_order_item.quantity
     *
     * @return the value of ykt_order_item.quantity
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_order_item.quantity
     *
     * @param quantity the value for ykt_order_item.quantity
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_order_item.is_alive
     *
     * @return the value of ykt_order_item.is_alive
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public Integer getIsAlive() {
        return isAlive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_order_item.is_alive
     *
     * @param isAlive the value for ykt_order_item.is_alive
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setIsAlive(Integer isAlive) {
        this.isAlive = isAlive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_order_item.user_id
     *
     * @return the value of ykt_order_item.user_id
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_order_item.user_id
     *
     * @param userId the value for ykt_order_item.user_id
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}