package com.dreamingCourse.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_order.id
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_order.user_id
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_order.payment
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private BigDecimal payment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_order.pay_type
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private Integer payType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_order.status
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_order.is_assess
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private Integer isAssess;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_order.pay_time
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private Date payTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_order.send_time
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private Date sendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_order.end_time
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_order.close_time
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private Date closeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_order.create_time
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_order.update_time
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_order.is_alive
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private Integer isAlive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_order.order_number
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private String orderNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_order.id
     *
     * @return the value of ykt_order.id
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_order.id
     *
     * @param id the value for ykt_order.id
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_order.user_id
     *
     * @return the value of ykt_order.user_id
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_order.user_id
     *
     * @param userId the value for ykt_order.user_id
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_order.payment
     *
     * @return the value of ykt_order.payment
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public BigDecimal getPayment() {
        return payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_order.payment
     *
     * @param payment the value for ykt_order.payment
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setPayment(BigDecimal payment) {
        this.payment = payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_order.pay_type
     *
     * @return the value of ykt_order.pay_type
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public Integer getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_order.pay_type
     *
     * @param payType the value for ykt_order.pay_type
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setPayType(Integer payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_order.status
     *
     * @return the value of ykt_order.status
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_order.status
     *
     * @param status the value for ykt_order.status
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_order.is_assess
     *
     * @return the value of ykt_order.is_assess
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public Integer getIsAssess() {
        return isAssess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_order.is_assess
     *
     * @param isAssess the value for ykt_order.is_assess
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setIsAssess(Integer isAssess) {
        this.isAssess = isAssess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_order.pay_time
     *
     * @return the value of ykt_order.pay_time
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_order.pay_time
     *
     * @param payTime the value for ykt_order.pay_time
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_order.send_time
     *
     * @return the value of ykt_order.send_time
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_order.send_time
     *
     * @param sendTime the value for ykt_order.send_time
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_order.end_time
     *
     * @return the value of ykt_order.end_time
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_order.end_time
     *
     * @param endTime the value for ykt_order.end_time
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_order.close_time
     *
     * @return the value of ykt_order.close_time
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public Date getCloseTime() {
        return closeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_order.close_time
     *
     * @param closeTime the value for ykt_order.close_time
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setCloseTime(Date closeTime) {
        this.closeTime = closeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_order.create_time
     *
     * @return the value of ykt_order.create_time
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_order.create_time
     *
     * @param createTime the value for ykt_order.create_time
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_order.update_time
     *
     * @return the value of ykt_order.update_time
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_order.update_time
     *
     * @param updateTime the value for ykt_order.update_time
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_order.is_alive
     *
     * @return the value of ykt_order.is_alive
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public Integer getIsAlive() {
        return isAlive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_order.is_alive
     *
     * @param isAlive the value for ykt_order.is_alive
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setIsAlive(Integer isAlive) {
        this.isAlive = isAlive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_order.order_number
     *
     * @return the value of ykt_order.order_number
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public String getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_order.order_number
     *
     * @param orderNumber the value for ykt_order.order_number
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber == null ? null : orderNumber.trim();
    }
}