package com.dreamingCourse.entity;

import java.util.Date;

public class PayInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_pay_info.id
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_pay_info.order_id
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_pay_info.pay_platform
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private Integer payPlatform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_pay_info.platform_number
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private String platformNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_pay_info.pay_status
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private String payStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_pay_info.create_time
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_pay_info.update_time
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_pay_info.is_alive
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private Integer isAlive;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_pay_info.id
     *
     * @return the value of ykt_pay_info.id
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_pay_info.id
     *
     * @param id the value for ykt_pay_info.id
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_pay_info.order_id
     *
     * @return the value of ykt_pay_info.order_id
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_pay_info.order_id
     *
     * @param orderId the value for ykt_pay_info.order_id
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_pay_info.pay_platform
     *
     * @return the value of ykt_pay_info.pay_platform
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public Integer getPayPlatform() {
        return payPlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_pay_info.pay_platform
     *
     * @param payPlatform the value for ykt_pay_info.pay_platform
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setPayPlatform(Integer payPlatform) {
        this.payPlatform = payPlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_pay_info.platform_number
     *
     * @return the value of ykt_pay_info.platform_number
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public String getPlatformNumber() {
        return platformNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_pay_info.platform_number
     *
     * @param platformNumber the value for ykt_pay_info.platform_number
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setPlatformNumber(String platformNumber) {
        this.platformNumber = platformNumber == null ? null : platformNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_pay_info.pay_status
     *
     * @return the value of ykt_pay_info.pay_status
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public String getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_pay_info.pay_status
     *
     * @param payStatus the value for ykt_pay_info.pay_status
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setPayStatus(String payStatus) {
        this.payStatus = payStatus == null ? null : payStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_pay_info.create_time
     *
     * @return the value of ykt_pay_info.create_time
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_pay_info.create_time
     *
     * @param createTime the value for ykt_pay_info.create_time
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_pay_info.update_time
     *
     * @return the value of ykt_pay_info.update_time
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_pay_info.update_time
     *
     * @param updateTime the value for ykt_pay_info.update_time
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_pay_info.is_alive
     *
     * @return the value of ykt_pay_info.is_alive
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public Integer getIsAlive() {
        return isAlive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_pay_info.is_alive
     *
     * @param isAlive the value for ykt_pay_info.is_alive
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setIsAlive(Integer isAlive) {
        this.isAlive = isAlive;
    }
}