package com.dreamingCourse.entity;

import java.util.Date;

public class ReceiveInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_receive_info.id
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_receive_info.user_id
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_receive_info.user_province
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private String userProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_receive_info.user_city
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private String userCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_receive_info.user_district
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private String userDistrict;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_receive_info.user_address
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private String userAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_receive_info.user_zip
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private String userZip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_receive_info.create_time
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_receive_info.update_time
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_receive_info.is_alive
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private Integer isAlive;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_receive_info.id
     *
     * @return the value of ykt_receive_info.id
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_receive_info.id
     *
     * @param id the value for ykt_receive_info.id
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_receive_info.user_id
     *
     * @return the value of ykt_receive_info.user_id
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_receive_info.user_id
     *
     * @param userId the value for ykt_receive_info.user_id
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_receive_info.user_province
     *
     * @return the value of ykt_receive_info.user_province
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public String getUserProvince() {
        return userProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_receive_info.user_province
     *
     * @param userProvince the value for ykt_receive_info.user_province
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setUserProvince(String userProvince) {
        this.userProvince = userProvince == null ? null : userProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_receive_info.user_city
     *
     * @return the value of ykt_receive_info.user_city
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public String getUserCity() {
        return userCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_receive_info.user_city
     *
     * @param userCity the value for ykt_receive_info.user_city
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setUserCity(String userCity) {
        this.userCity = userCity == null ? null : userCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_receive_info.user_district
     *
     * @return the value of ykt_receive_info.user_district
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public String getUserDistrict() {
        return userDistrict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_receive_info.user_district
     *
     * @param userDistrict the value for ykt_receive_info.user_district
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setUserDistrict(String userDistrict) {
        this.userDistrict = userDistrict == null ? null : userDistrict.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_receive_info.user_address
     *
     * @return the value of ykt_receive_info.user_address
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public String getUserAddress() {
        return userAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_receive_info.user_address
     *
     * @param userAddress the value for ykt_receive_info.user_address
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress == null ? null : userAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_receive_info.user_zip
     *
     * @return the value of ykt_receive_info.user_zip
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public String getUserZip() {
        return userZip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_receive_info.user_zip
     *
     * @param userZip the value for ykt_receive_info.user_zip
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setUserZip(String userZip) {
        this.userZip = userZip == null ? null : userZip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_receive_info.create_time
     *
     * @return the value of ykt_receive_info.create_time
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_receive_info.create_time
     *
     * @param createTime the value for ykt_receive_info.create_time
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_receive_info.update_time
     *
     * @return the value of ykt_receive_info.update_time
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_receive_info.update_time
     *
     * @param updateTime the value for ykt_receive_info.update_time
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_receive_info.is_alive
     *
     * @return the value of ykt_receive_info.is_alive
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public Integer getIsAlive() {
        return isAlive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_receive_info.is_alive
     *
     * @param isAlive the value for ykt_receive_info.is_alive
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setIsAlive(Integer isAlive) {
        this.isAlive = isAlive;
    }
}