package com.dreamingCourse.entity;

import java.util.Date;

public class SecKill {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_seckill.id
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_seckill.c_name
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private String cName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_seckill.price
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private Long price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_seckill.number
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private Integer number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_seckill.start_time
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_seckill.end_time
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_seckill.create_time
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_seckill.is_alive
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private Integer isAlive;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_seckill.id
     *
     * @return the value of ykt_seckill.id
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_seckill.id
     *
     * @param id the value for ykt_seckill.id
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_seckill.c_name
     *
     * @return the value of ykt_seckill.c_name
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public String getcName() {
        return cName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_seckill.c_name
     *
     * @param cName the value for ykt_seckill.c_name
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setcName(String cName) {
        this.cName = cName == null ? null : cName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_seckill.price
     *
     * @return the value of ykt_seckill.price
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_seckill.price
     *
     * @param price the value for ykt_seckill.price
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_seckill.number
     *
     * @return the value of ykt_seckill.number
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_seckill.number
     *
     * @param number the value for ykt_seckill.number
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_seckill.start_time
     *
     * @return the value of ykt_seckill.start_time
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_seckill.start_time
     *
     * @param startTime the value for ykt_seckill.start_time
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_seckill.end_time
     *
     * @return the value of ykt_seckill.end_time
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_seckill.end_time
     *
     * @param endTime the value for ykt_seckill.end_time
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_seckill.create_time
     *
     * @return the value of ykt_seckill.create_time
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_seckill.create_time
     *
     * @param createTime the value for ykt_seckill.create_time
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_seckill.is_alive
     *
     * @return the value of ykt_seckill.is_alive
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public Integer getIsAlive() {
        return isAlive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_seckill.is_alive
     *
     * @param isAlive the value for ykt_seckill.is_alive
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setIsAlive(Integer isAlive) {
        this.isAlive = isAlive;
    }
}