package com.dreamingCourse.entity;

import java.util.Date;

public class SuccessKilled {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_success_killed.id
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_success_killed.user_id
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_success_killed.state
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private Byte state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_success_killed.create_time
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_success_killed.order_id
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_success_killed.is_alive
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private Integer isAlive;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_success_killed.id
     *
     * @return the value of ykt_success_killed.id
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_success_killed.id
     *
     * @param id the value for ykt_success_killed.id
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_success_killed.user_id
     *
     * @return the value of ykt_success_killed.user_id
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_success_killed.user_id
     *
     * @param userId the value for ykt_success_killed.user_id
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_success_killed.state
     *
     * @return the value of ykt_success_killed.state
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_success_killed.state
     *
     * @param state the value for ykt_success_killed.state
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_success_killed.create_time
     *
     * @return the value of ykt_success_killed.create_time
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_success_killed.create_time
     *
     * @param createTime the value for ykt_success_killed.create_time
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_success_killed.order_id
     *
     * @return the value of ykt_success_killed.order_id
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_success_killed.order_id
     *
     * @param orderId the value for ykt_success_killed.order_id
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_success_killed.is_alive
     *
     * @return the value of ykt_success_killed.is_alive
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public Integer getIsAlive() {
        return isAlive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_success_killed.is_alive
     *
     * @param isAlive the value for ykt_success_killed.is_alive
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setIsAlive(Integer isAlive) {
        this.isAlive = isAlive;
    }
}