package com.dreamingCourse.entity;

public class Teacher {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_teacher.id
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_teacher.t_name
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private String tName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_teacher.t_desc
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private String tDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_teacher.t_image
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private String tImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_teacher.cources_id
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private Integer courcesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_teacher.is_alive
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private Integer isAlive;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_teacher.id
     *
     * @return the value of ykt_teacher.id
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_teacher.id
     *
     * @param id the value for ykt_teacher.id
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_teacher.t_name
     *
     * @return the value of ykt_teacher.t_name
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public String gettName() {
        return tName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_teacher.t_name
     *
     * @param tName the value for ykt_teacher.t_name
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void settName(String tName) {
        this.tName = tName == null ? null : tName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_teacher.t_desc
     *
     * @return the value of ykt_teacher.t_desc
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public String gettDesc() {
        return tDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_teacher.t_desc
     *
     * @param tDesc the value for ykt_teacher.t_desc
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void settDesc(String tDesc) {
        this.tDesc = tDesc == null ? null : tDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_teacher.t_image
     *
     * @return the value of ykt_teacher.t_image
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public String gettImage() {
        return tImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_teacher.t_image
     *
     * @param tImage the value for ykt_teacher.t_image
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void settImage(String tImage) {
        this.tImage = tImage == null ? null : tImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_teacher.cources_id
     *
     * @return the value of ykt_teacher.cources_id
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public Integer getCourcesId() {
        return courcesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_teacher.cources_id
     *
     * @param courcesId the value for ykt_teacher.cources_id
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setCourcesId(Integer courcesId) {
        this.courcesId = courcesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_teacher.is_alive
     *
     * @return the value of ykt_teacher.is_alive
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public Integer getIsAlive() {
        return isAlive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_teacher.is_alive
     *
     * @param isAlive the value for ykt_teacher.is_alive
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setIsAlive(Integer isAlive) {
        this.isAlive = isAlive;
    }
}