package com.dreamingCourse.entity;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_user.id
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_user.username
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_user.password
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_user.email
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_user.phone
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_user.question
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private String question;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_user.answer
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private String answer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_user.role
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private Integer role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_user.image
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_user.code
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_user.create_time
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_user.update_time
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ykt_user.is_alive
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    private Integer isAlive;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_user.id
     *
     * @return the value of ykt_user.id
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_user.id
     *
     * @param id the value for ykt_user.id
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_user.username
     *
     * @return the value of ykt_user.username
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_user.username
     *
     * @param username the value for ykt_user.username
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_user.password
     *
     * @return the value of ykt_user.password
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_user.password
     *
     * @param password the value for ykt_user.password
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_user.email
     *
     * @return the value of ykt_user.email
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_user.email
     *
     * @param email the value for ykt_user.email
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_user.phone
     *
     * @return the value of ykt_user.phone
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_user.phone
     *
     * @param phone the value for ykt_user.phone
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_user.question
     *
     * @return the value of ykt_user.question
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_user.question
     *
     * @param question the value for ykt_user.question
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setQuestion(String question) {
        this.question = question == null ? null : question.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_user.answer
     *
     * @return the value of ykt_user.answer
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_user.answer
     *
     * @param answer the value for ykt_user.answer
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_user.role
     *
     * @return the value of ykt_user.role
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public Integer getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_user.role
     *
     * @param role the value for ykt_user.role
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setRole(Integer role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_user.image
     *
     * @return the value of ykt_user.image
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_user.image
     *
     * @param image the value for ykt_user.image
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_user.code
     *
     * @return the value of ykt_user.code
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_user.code
     *
     * @param code the value for ykt_user.code
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_user.create_time
     *
     * @return the value of ykt_user.create_time
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_user.create_time
     *
     * @param createTime the value for ykt_user.create_time
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_user.update_time
     *
     * @return the value of ykt_user.update_time
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_user.update_time
     *
     * @param updateTime the value for ykt_user.update_time
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ykt_user.is_alive
     *
     * @return the value of ykt_user.is_alive
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public Integer getIsAlive() {
        return isAlive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ykt_user.is_alive
     *
     * @param isAlive the value for ykt_user.is_alive
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    public void setIsAlive(Integer isAlive) {
        this.isAlive = isAlive;
    }
}