package com.dreamingCourse.mapper;

import com.dreamingCourse.entity.Cart;

import java.util.List;

public interface CartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ykt_cart
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ykt_cart
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    int insert(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ykt_cart
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    Cart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ykt_cart
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    List<Cart> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ykt_cart
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    int updateByPrimaryKey(Cart record);
}