package com.dreamingCourse.mapper;

import com.dreamingCourse.entity.Course;

import java.util.List;

public interface CourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ykt_course
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ykt_course
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    int insert(Course record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ykt_course
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    Course selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ykt_course
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    List<Course> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ykt_course
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    int updateByPrimaryKey(Course record);
}