package com.dreamingCourse.mapper;

import com.dreamingCourse.entity.Lists;

import java.util.List;

public interface ListsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ykt_lists
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ykt_lists
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    int insert(Lists record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ykt_lists
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    Lists selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ykt_lists
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    List<Lists> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ykt_lists
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    int updateByPrimaryKey(Lists record);
}