package com.dreamingCourse.mapper;

import com.dreamingCourse.entity.Notice;

import java.util.List;

public interface NoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ykt_notice
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    Notice deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ykt_notice
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    Notice insert(Notice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ykt_notice
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    Notice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ykt_notice
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    List<Notice> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ykt_notice
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    Notice updateByPrimaryKey(Notice record);
}