package com.dreamingCourse.mapper;

import com.dreamingCourse.entity.PayInfo;

import java.util.List;

public interface PayInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ykt_pay_info
     *
     * @mbggenerated Mon Aug 12 20:20:16 CST 2019
     */
    PayInfo deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ykt_pay_info
     *
     * @mbggenerated Mon Aug 12 20:20:16 CST 2019
     */
    PayInfo insert(PayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ykt_pay_info
     *
     * @mbggenerated Mon Aug 12 20:20:16 CST 2019
     */
    PayInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ykt_pay_info
     *
     * @mbggenerated Mon Aug 12 20:20:16 CST 2019
     */
    List<PayInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ykt_pay_info
     *
     * @mbggenerated Mon Aug 12 20:20:16 CST 2019
     */
    PayInfo updateByPrimaryKey(PayInfo record);
}