package com.dreamingCourse.mapper;

import com.dreamingCourse.entity.SecKill;

import java.util.List;

public interface SecKillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ykt_seckill
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ykt_seckill
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    int insert(SecKill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ykt_seckill
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    SecKill selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ykt_seckill
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    List<SecKill> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ykt_seckill
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    int updateByPrimaryKey(SecKill record);
}