package com.dreamingCourse.mapper;

import com.dreamingCourse.entity.SuccessKilled;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SuccessKilledMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ykt_success_killed
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    int deleteByPrimaryKey(@Param("id") Integer id, @Param("userId") Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ykt_success_killed
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    int insert(SuccessKilled record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ykt_success_killed
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    SuccessKilled selectByPrimaryKey(@Param("id") Integer id, @Param("userId") Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ykt_success_killed
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    List<SuccessKilled> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ykt_success_killed
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    int updateByPrimaryKey(SuccessKilled record);
}