package com.dreamingCourse.mapper;

import com.dreamingCourse.entity.Tag;

import java.util.List;

public interface TagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ykt_tag
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ykt_tag
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    int insert(Tag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ykt_tag
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    Tag selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ykt_tag
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    List<Tag> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ykt_tag
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    int updateByPrimaryKey(Tag record);
}