package com.dreamingCourse.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.dreamingCourse.entity.Tag;
import com.dreamingCourse.entity.Ykt_tag;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface TagMapper extends  BaseMapper<Ykt_tag> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ykt_tag
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ykt_tag
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    int insert(Tag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ykt_tag
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    Tag selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ykt_tag
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    List<Tag> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ykt_tag
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    int updateByPrimaryKey(Tag record);
}