package com.dreamingCourse.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.dreamingCourse.entity.Teacher;
import com.dreamingCourse.entity.Ykt_teacher;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface TeacherMapper extends BaseMapper<Ykt_teacher> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ykt_teacher
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    Teacher deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ykt_teacher
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    Teacher insert(Teacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ykt_teacher
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    Teacher selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ykt_teacher
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    List<Teacher> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ykt_teacher
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    Teacher updateByPrimaryKey(Teacher record);
}

