package com.dreamingCourse.mapper;

import com.dreamingCourse.entity.User;

import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ykt_user
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ykt_user
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ykt_user
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ykt_user
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ykt_user
     *
     * @mbggenerated Tue Jul 30 17:00:31 CST 2019
     */
    int updateByPrimaryKey(User record);
}